'use strict';

const DECISION_TRIGGER = Object.freeze({
  STATE_CHANGED: 'STATE_CHANGED',
  EXPECTATION_OVERDUE: 'EXPECTATION_OVERDUE',
  EXPECTATION_OPEN: 'EXPECTATION_OPEN',
  NEW_EVIDENCE: 'NEW_EVIDENCE',
  AO_UPDATE: 'AO_UPDATE',
  AGENT_RESULT: 'AGENT_RESULT',
  MISSION_STATE_CHANGED: 'MISSION_STATE_CHANGED',
  SCHEDULED_REVIEW: 'SCHEDULED_REVIEW',
  OPERATOR_REQUEST: 'OPERATOR_REQUEST',
  SYSTEM_FAILURE: 'SYSTEM_FAILURE',
});

const AUTHORITY_CLASS = Object.freeze({
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
});

const ACTION_TYPE = Object.freeze({
  NO_ACTION: 'NO_ACTION',
  ASK_AO_STATUS: 'ASK_AO_STATUS',
  CREATE_AO_TASK: 'CREATE_AO_TASK',
  ESCALATE_OPERATOR: 'ESCALATE_OPERATOR',
  DELEGATE_AGENT: 'DELEGATE_AGENT',
  SEEK_CLARIFICATION: 'SEEK_CLARIFICATION',
  ABSTAIN_INSUFFICIENT_EVIDENCE: 'ABSTAIN_INSUFFICIENT_EVIDENCE',
  EXECUTE_INTERNAL_UPDATE: 'EXECUTE_INTERNAL_UPDATE',
  RETURN_TO_COLD_OUTREACH: 'RETURN_TO_COLD_OUTREACH',
  RESOLVE_EXPECTATION: 'RESOLVE_EXPECTATION',
  SUPERSEDE_PRIOR: 'SUPERSEDE_PRIOR',
});

const EXECUTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  EXECUTION_BLOCKED: 'EXECUTION_BLOCKED',
  EXECUTING: 'EXECUTING',
  EXECUTED: 'EXECUTED',
  ACTION_ALREADY_ACTIVE: 'ACTION_ALREADY_ACTIVE',
  ACTION_VERIFICATION_FAILED: 'ACTION_VERIFICATION_FAILED',
  EXECUTION_FAILURE: 'EXECUTION_FAILURE',
  SUPERSEDED: 'SUPERSEDED',
  NO_ACTION_RECORDED: 'NO_ACTION_RECORDED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
});

const VERIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

const EPISTEMIC = Object.freeze({
  KNOWN: 'KNOWN',
  INFERRED: 'INFERRED',
  UNKNOWN: 'UNKNOWN',
  CONFLICTING: 'CONFLICTING',
});

const SUBJECT_TYPE = Object.freeze({
  PROSPECT: 'prospect',
  EXPECTATION: 'expectation',
  ACCOUNT: 'account',
  MISSION: 'mission',
});

module.exports = {
  DECISION_TRIGGER,
  AUTHORITY_CLASS,
  ACTION_TYPE,
  EXECUTION_STATUS,
  VERIFICATION_STATUS,
  EPISTEMIC,
  SUBJECT_TYPE,
};
