'use strict';

/**
 * SPEC-102F — canonical Max competency catalog.
 * Implementation specs encode behavior; this registry tracks maturation.
 */

const { STAGES } = require('./CompetencyLifecycle');

const CATEGORIES = Object.freeze({
  CORE_MANAGEMENT: 'core_management',
  ARBITRATION: 'arbitration',
  PLANNING: 'planning',
  ECONOMICS: 'economics',
});

/** @type {import('./TrainingExercise').CompetencyDefinition[]} */
const COMPETENCIES = Object.freeze([
  {
    id: 'retrieve_before_delegation',
    label: 'Retrieve Before Delegation',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-16',
    specRefs: ['SPEC-102', 'SPEC-103'],
    regressionTests: [
      'test/retrievalBeforeDelegation.test.js',
      'packages/max/workspace/tests/retrievalBeforeDelegation.test.js',
      'packages/max/workspace/tests/businessUnderstandingRetrieval.test.js',
    ],
    exercises: [{
      id: 'service_area_retrieval',
      assignment: 'What do you currently understand about our service area?',
      observedBehavior: 'Delegated to Scout instead of retrieving durable knowledge.',
      expectedBehavior: 'Answer from Blueprint / Playbook / KG / prior investigations, or say unknown.',
      failureMode: 'Question → Scout without retrieval attempt.',
      generalLesson: 'Do not delegate work Max can already answer.',
      retest: 'What do you currently understand about our service area?',
      transferTest: 'What do you know about Kumho Tire?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-16',
      specRef: 'SPEC-102',
    }],
  },
  {
    id: 'delegation_discipline',
    label: 'Delegation Discipline',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-16',
    specRefs: ['SPEC-098'],
    regressionTests: [
      'packages/max/workspace/tests/specialistDelegation.test.js',
    ],
    exercises: [],
  },
  {
    id: 'specialist_evaluation',
    label: 'Specialist Evaluation',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-16',
    specRefs: ['SPEC-100', 'SPEC-098'],
    regressionTests: [
      'packages/max/workspace/tests/scoutAcquisition.test.js',
    ],
    exercises: [],
  },
  {
    id: 'investigation_coverage_reasoning',
    label: 'Investigation Coverage Reasoning',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-16',
    specRefs: ['SPEC-099A'],
    regressionTests: [
      'test/scoutInvestigationProvenance.test.js',
    ],
    exercises: [{
      id: 'coverage_vs_conclusion',
      assignment: 'Where should we look for commercial cleaning opportunities?',
      observedBehavior: 'Delegated correctly; coverage reasoning missing.',
      expectedBehavior: 'Evaluate investigation quality separately from conclusions.',
      failureMode: 'Treat zero results and weak coverage as equivalent.',
      generalLesson: 'A specialist conclusion and the quality of the investigation are separate.',
      retest: 'Where should we look for commercial cleaning opportunities?',
      transferTest: 'Scout found zero — was the investigation thorough?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-16',
      specRef: 'SPEC-099A',
    }],
  },
  {
    id: 'specialist_trace_interrogation',
    label: 'Specialist Trace Interrogation',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-16',
    specRefs: ['SPEC-101'],
    regressionTests: [
      'packages/max/workspace/tests/specialistInterrogation.test.js',
    ],
    exercises: [],
  },
  {
    id: 'explain_uncertainty',
    label: 'Explain Uncertainty',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-16',
    specRefs: ['SPEC-101', 'SPEC-099A'],
    regressionTests: [
      'packages/max/workspace/tests/specialistInterrogation.test.js',
    ],
    exercises: [],
  },
  {
    id: 'evidence_separation',
    label: 'Evidence Separation',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-16',
    specRefs: ['SPEC-101', 'SPEC-099A'],
    regressionTests: [
      'packages/max/workspace/tests/specialistInterrogation.test.js',
    ],
    exercises: [],
  },
  {
    id: 'durable_business_understanding',
    label: 'Durable Business Understanding',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-17',
    specRefs: ['SPEC-103', 'SPEC-083', 'SPEC-084'],
    regressionTests: [
      'packages/max/workspace/tests/businessUnderstandingRetrieval.test.js',
      'packages/max/workspace/tests/clientIntelligenceContinuity.test.js',
    ],
    exercises: [{
      id: 'anchor_blueprint_recall',
      assignment: 'What do you currently understand about Anchor Cleaning?',
      observedBehavior: 'Answered "I don\'t currently know" despite approved Blueprint in store.',
      expectedBehavior: 'Rich business summary from approved Blueprint without delegating.',
      failureMode: 'Session-only retrieval — durable Blueprint never loaded.',
      generalLesson: 'Business understanding must be retrieved from persistent stores, not session stubs.',
      retest: 'What do you currently understand about Anchor Cleaning?',
      transferTest: 'What is our service area?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-17',
      specRef: 'SPEC-103',
    }],
  },
  {
    id: 'intent_bound_response_selection',
    label: 'Intent-Bound Response Selection',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-18',
    specRefs: ['SPEC-109', 'SPEC-107', 'SPEC-102'],
    regressionTests: [
      'test/intentBoundResponseSelection.test.js',
      'packages/max/workspace/tests/intentBoundResponseSelection.test.js',
    ],
    exercises: [{
      id: 'completed_recently_is_retrieval',
      assignment: 'What have we completed recently?',
      observedBehavior: 'Returned a Blueprint acquisition recommendation instead of completed operating state.',
      expectedBehavior: 'Select the Retrieval contract before reasoning. Answer verified state and unknowns first. Do not lead with unsolicited strategy.',
      failureMode: 'Advice as a universal response type — retrieve then recommend regardless of intent.',
      generalLesson: 'Operator intent determines response structure. Evidence determines content. Reasoning determines recommendations. Those are separate stages.',
      retest: 'What have we completed recently?',
      transferTest: 'What outreach has already been sent? How is Anchor Cleaning doing? What should we do next? That\'s incorrect. Investigate commercial prospects.',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-18',
      specRef: 'SPEC-109',
    }],
  },
  {
    id: 'claim_grounding',
    label: 'Claim Grounding',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-18',
    specRefs: ['SPEC-108', 'SPEC-107A', 'SPEC-107'],
    regressionTests: [
      'test/recommendationClaimGrounding.test.js',
      'test/claimGrounding.test.js',
      'packages/max/workspace/tests/recommendationClaimGrounding.test.js',
      'packages/max/workspace/tests/claimGrounding.test.js',
    ],
    exercises: [{
      id: 'unsupported_operating_state_retraction',
      assignment: 'Given what is already in motion, what should I focus on next? Then: You said outbound email is already active. What evidence tells you that?',
      observedBehavior: 'Asserted an active email motion from inventory, then restated inventory when challenged.',
      expectedBehavior: 'Evaluate operating-state claims against evidence before recommending. Retract unsupported claims and revise the recommendation.',
      failureMode: 'Treat planned work, inventory, or objectives as observed execution.',
      generalLesson: 'Recommendations may only depend on supported operating-state claims. Planned is not completed; inventory is not execution; goals are not operating state.',
      retest: 'You said outbound email is already active. What evidence tells you that?',
      transferTest: 'Follow-up is scheduled tomorrow — did it occur? 67 prospects exist — has outreach begun? Blueprint says acquire twenty commercial clients — are you expanding?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-18',
      specRef: 'SPEC-108',
    }],
  },
  {
    id: 'business_intelligence_synthesis',
    label: 'Business Intelligence Synthesis',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-18',
    specRefs: ['SPEC-110', 'SPEC-109', 'SPEC-108', 'SPEC-107'],
    regressionTests: [
      'test/businessIntelligenceSynthesis.test.js',
      'packages/max/workspace/tests/businessIntelligenceSynthesis.test.js',
    ],
    exercises: [{
      id: 'anchor_inventory_is_not_intelligence',
      assignment: 'How is Anchor Cleaning doing?',
      observedBehavior: 'Returned a raw inventory (72 prospects, 69 Scout companies, 20 AO leads) and left the operator to reason.',
      expectedBehavior: 'Synthesize first-class business intelligence objects from grounded claims, present conclusions first, then supporting evidence. Never speculate when evidence is insufficient.',
      failureMode: 'Evidence presentation as the response — retrieve and list counts without identifying bottlenecks, progress, readiness, risk, or unknowns.',
      generalLesson: 'Evidence exists to support intelligence. Intelligence exists to support operator decisions. Max should communicate conclusions, not merely inventories.',
      retest: 'How is Anchor Cleaning doing?',
      transferTest: 'What outreach has already been sent? What should we do next? Are Yelp Ads working? Where should we focus next?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-18',
      specRef: 'SPEC-110',
    }],
  },
  {
    id: 'operator_intent_taxonomy',
    label: 'Operator Intent Taxonomy',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-18',
    specRefs: ['SPEC-111', 'SPEC-110', 'SPEC-109'],
    regressionTests: [
      'test/operatorIntentTaxonomy.test.js',
      'packages/max/workspace/tests/operatorIntentTaxonomy.test.js',
    ],
    exercises: [{
      id: 'diagnosis_is_not_recommendation',
      assignment: "What's preventing us from growing faster?",
      observedBehavior: 'Collapsed diagnosis into a Blueprint acquisition recommendation.',
      expectedBehavior: 'Classify Diagnosis before reasoning. Identify the current bottleneck from business intelligence. Do not lead with generic commercial acquisition advice.',
      failureMode: 'Intent routing treats diagnostic questions as Recommendation or Unknown Analysis as a Scout shortcut.',
      generalLesson: 'Intent determines analysis. Analysis determines reasoning. Reasoning determines response. Operators ask for different forms of intelligence.',
      retest: "What's preventing us from growing faster?",
      transferTest: "What don't we know yet that matters? What's our biggest operational risk? How much progress have we made? What should we do next?",
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-18',
      specRef: 'SPEC-111',
    }],
  },
  {
    id: 'acquisition_intelligence_model',
    label: 'Acquisition Intelligence Model',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-18',
    specRefs: ['SPEC-112', 'SPEC-100', 'SPEC-100A'],
    regressionTests: [
      'packages/aim/tests/aim.test.js',
      'test/acquisitionIntelligenceModel.test.js',
    ],
    exercises: [{
      id: 'understand_market_before_selling',
      assignment: 'Qualify founder-led businesses for Fedir before outreach.',
      observedBehavior: 'Scout searched demographics. Paige started from a blank prompt. Qualification was a single ICP number.',
      expectedBehavior: 'Load the AIM. Reason over mission, ICP, transformation, and pain signals. Score ICP Fit, Pain Match, Evidence Quality, Buying Readiness, Confidence, and Recommendation. Give Paige pain, language, proof (or unknown), and CTA.',
      failureMode: 'Search the market before understanding it. Invent case studies. Treat AIM findings as operating fact.',
      generalLesson: 'PulseForge should understand a market before it attempts to sell into it. Scout reasons. Paige never starts from zero when AIM qualification exists.',
      retest: 'Qualify a founder-led agency whose owner replies to reviews and is hiring repeatedly.',
      transferTest: 'A PE-backed enterprise HQ appears in the list — do we pursue? Paige sees Founder Dependency 92% — what does she already know?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-18',
      specRef: 'SPEC-112',
    }],
  },
  {
    id: 'acquisition_intelligence_compiler',
    label: 'Acquisition Intelligence Compiler',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-18',
    specRefs: ['SPEC-113', 'SPEC-112', 'SPEC-083'],
    regressionTests: [
      'packages/aic/tests/aic.test.js',
      'test/acquisitionIntelligenceCompiler.test.js',
    ],
    exercises: [{
      id: 'compile_market_knowledge_before_runtime',
      assignment: 'Turn pain research, a customer interview, and a landing page into Scout runtime knowledge.',
      observedBehavior: 'Scout reread PDFs. Extracted prose was treated as an answer. Understanding disappeared after the prompt.',
      expectedBehavior: 'Ingest documents. Extract concepts with provenance. Build the ontology. Wait for operator accept/edit/merge/remove. Publish an AIM. Scout loads that published AIM — never the documents.',
      failureMode: 'Auto-publish after extract. Invent mission or geography. Let Scout search from raw files. Execute outreach from the compiler.',
      generalLesson: 'Market knowledge is compiled, then approved, then published. Understanding becomes durable. The compiler never executes outreach.',
      retest: 'Upload Pain Points v3 plus Interview #12. Approve Founder Dependency supported by Hiring observed through Job Posts. Publish. Qualify a hiring founder-led agency.',
      transferTest: 'A draft AIM exists but is not published — does Scout reason over it? Can the compiler send the first email?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-18',
      specRef: 'SPEC-113',
    }],
  },
  {
    id: 'client_tenant_creation',
    label: 'Client Tenant Creation & Activation',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-18',
    specRefs: ['SPEC-114', 'SPEC-083', 'SPEC-112', 'SPEC-113'],
    regressionTests: [
      'test/tenantWorkspace.test.js',
    ],
    exercises: [{
      id: 'provision_tenant_before_intelligence',
      assignment: 'Create Fedir as a live tenant and start onboarding without touching the database.',
      observedBehavior: 'New clients required a developer INSERT. Max defaulted to Pulseforge. Seed AIM looked like a tenant.',
      expectedBehavior: 'Operator creates the client. PulseForge provisions isolated namespaces. Workspace starts empty. Activate Fedir. Max executes inside that tenant and greets with Client Intelligence first.',
      failureMode: 'Copy Pulseforge intelligence. Attach the hand-authored Fedir AIM seed. Invent prospects. Let Max run with no tenant selected.',
      generalLesson: 'A tenant is provisioned before intelligence begins. Every new workspace starts empty. No tenant means fail closed.',
      retest: 'Create Fedir. Activate Fedir. Confirm Client Intelligence is Not Started and AIM is No Published AIM. Ask Max without a tenant — he refuses.',
      transferTest: 'Create a second tenant. Can it see Fedir prospects? Does Max still greet as Fedir after you switch away?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-18',
      specRef: 'SPEC-114',
    }],
  },
  {
    id: 'pilot_0_client_onboarding',
    label: 'Pilot 0 Self-Service Client Onboarding',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-19',
    specRefs: ['SPEC-115', 'SPEC-114', 'SPEC-113', 'SPEC-083'],
    regressionTests: [
      'test/pilotOnboarding.test.js',
    ],
    exercises: [{
      id: 'admin_provisioned_pilot_onboarding',
      assignment: 'An admin provisions a brand-new client in the product. The client logs in with a temporary password, is forced to choose a new one, completes Client Intelligence, publishes an AIM, asks Max, and Scout returns tenant-scoped prospects — no SQL.',
      observedBehavior: 'Onboarding required a developer to INSERT users, hash passwords, activate tenants, and publish AIM records by hand.',
      expectedBehavior: 'Admin creates tenant and user with a temporary password. First login forces a password change. Guided workspace: CIE → Blueprint → AIM compile/review/publish → Max → Scout. Failures are explicit. Max does not pretend to know the business.',
      failureMode: 'Skip the password change. Let Max answer without a Blueprint and published AIM. Run Scout across tenants. Require SQL or a runbook.',
      generalLesson: 'Developer intervention is a product bug. Pilot 0 validates that the platform can onboard a real customer through its own interfaces.',
      retest: 'Create tenant. Create client user with temporary password. Login. Change password. Complete CIE. Publish AIM. Ask Max. Run Scout. Confirm prospects carry that client_id.',
      transferTest: 'Can another tenant see those prospects? Does Max answer before AIM is published?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-19',
      specRef: 'SPEC-115',
    }],
  },
  {
    id: 'client_registration_workspace',
    label: 'Client Registration & Workspace Provisioning',
    category: CATEGORIES.CORE_MANAGEMENT,
    stage: STAGES.GRADUATED,
    graduatedAt: '2026-08-19',
    specRefs: ['SPEC-115', 'SPEC-114', 'SPEC-083'],
    regressionTests: [
      'test/registrationWorkspace.test.js',
    ],
    exercises: [{
      id: 'workspace_first_registration',
      assignment: 'A stranger creates an account, provisions a workspace, and reaches Max without touching Postgres.',
      observedBehavior: 'New customers required a developer to INSERT a user and a client. Login defaulted missing tenants to Pulseforge. Max opened with a generic welcome.',
      expectedBehavior: 'Sign up creates the workspace first. The user belongs to that workspace. Email is verified. Login lands on the dashboard. Max greets with Client Intelligence and one button. Intelligence starts empty.',
      failureMode: 'Create the user before the workspace. Default client-role login to Pulseforge. Invent a Blueprint or AIM. Skip verification. Require admin tools.',
      generalLesson: 'Registration is the beginning of Client Intelligence. The workspace is created first. Users belong to workspaces. Max never pretends to know the business.',
      retest: 'Register. Verify. Login. Confirm Blueprint Not Started, AIM none, counts at zero. Click Begin Client Intelligence.',
      transferTest: 'Can a second customer see the first workspace prospects? Does an unverified password open the dashboard?',
      graduationDecision: 'graduated',
      graduatedAt: '2026-08-19',
      specRef: 'SPEC-115',
    }],
  },
  {
    id: 'multi_specialist_arbitration',
    label: 'Multi-specialist Arbitration',
    category: CATEGORIES.ARBITRATION,
    stage: STAGES.TRAINING,
    specRefs: [],
    regressionTests: [],
    exercises: [],
  },
  {
    id: 'conflict_resolution',
    label: 'Conflict Resolution',
    category: CATEGORIES.ARBITRATION,
    stage: STAGES.NOT_STARTED,
    specRefs: [],
    regressionTests: [],
    exercises: [],
  },
  {
    id: 'long_horizon_planning',
    label: 'Long-horizon Planning',
    category: CATEGORIES.PLANNING,
    stage: STAGES.NOT_STARTED,
    specRefs: [],
    regressionTests: [],
    exercises: [],
  },
  {
    id: 'economic_tradeoff_reasoning',
    label: 'Economic Tradeoff Reasoning',
    category: CATEGORIES.ECONOMICS,
    stage: STAGES.NOT_STARTED,
    specRefs: [],
    regressionTests: [],
    exercises: [],
  },
  {
    id: 'opportunity_cost_analysis',
    label: 'Opportunity Cost Analysis',
    category: CATEGORIES.ECONOMICS,
    stage: STAGES.NOT_STARTED,
    specRefs: [],
    regressionTests: [],
    exercises: [],
  },
]);

function listCompetencies() {
  return COMPETENCIES.map(c => ({ ...c, exercises: c.exercises.map(e => ({ ...e })) }));
}

function getCompetency(id) {
  const found = COMPETENCIES.find(c => c.id === id);
  return found ? { ...found, exercises: found.exercises.map(e => ({ ...e })) } : null;
}

function listByCategory(category) {
  return listCompetencies().filter(c => c.category === category);
}

function listByStage(stage) {
  return listCompetencies().filter(c => c.stage === stage);
}

module.exports = {
  CATEGORIES,
  COMPETENCIES,
  listCompetencies,
  getCompetency,
  listByCategory,
  listByStage,
};
