'use strict';

const CHANGE_TYPES = Object.freeze({
  ADD_NOTE: 'ADD_NOTE',
  ADD_CONTACT: 'ADD_CONTACT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  ADD_PHONE: 'ADD_PHONE',
  ADD_EMAIL: 'ADD_EMAIL',
  UPDATE_ROLE: 'UPDATE_ROLE',
  ADD_PAIN_POINT: 'ADD_PAIN_POINT',
  ADD_OBJECTION: 'ADD_OBJECTION',
  UPDATE_DECISION_MAKER_SIGNAL: 'UPDATE_DECISION_MAKER_SIGNAL',
  ADD_FOLLOW_UP: 'ADD_FOLLOW_UP',
  UPDATE_NEXT_ACTION: 'UPDATE_NEXT_ACTION',
  UPDATE_DISPOSITION: 'UPDATE_DISPOSITION',
  CREATE_ACCOUNT_CANDIDATE: 'CREATE_ACCOUNT_CANDIDATE',
  SET_SALES_PRIORITY: 'SET_SALES_PRIORITY',
});

const ROW_CLASS = Object.freeze({
  EXISTING_ACCOUNT_UPDATE: 'existing_account_update',
  EXISTING_CONTACT_UPDATE: 'existing_contact_update',
  NEW_CONTACT: 'new_contact',
  NEW_ACCOUNT_CANDIDATE: 'new_account_candidate',
  ACTIVITY_NOTE: 'activity_note',
  FOLLOW_UP_UPDATE: 'follow_up_update',
  AMBIGUOUS: 'ambiguous',
  IGNORE_NON_OPERATIONAL: 'ignore_non_operational',
});

module.exports = {
  CHANGE_TYPES,
  ROW_CLASS,
};
