'use strict';

const SOURCE_TYPES = Object.freeze({
  OPERATOR_REPORTED: 'OPERATOR_REPORTED',
  AO_REPORTED: 'AO_REPORTED',
  SCOUT_DISCOVERED: 'SCOUT_DISCOVERED',
  AGENT_DERIVED: 'AGENT_DERIVED',
  FILE_IMPORTED: 'FILE_IMPORTED',
  SYSTEM_OBSERVED: 'SYSTEM_OBSERVED',
  API_OBSERVED: 'API_OBSERVED',
});

const RESOLUTION = Object.freeze({
  RESOLVED: 'RESOLVED',
  PROVISIONALLY_RESOLVED: 'PROVISIONALLY_RESOLVED',
  AMBIGUOUS: 'AMBIGUOUS',
  UNRESOLVED: 'UNRESOLVED',
  CONFLICT: 'CONFLICT',
  ALREADY_APPLIED: 'ALREADY_APPLIED',
});

const SAFETY_CLASS = Object.freeze({
  A: 'A',
  B: 'B',
  C: 'C',
});

const EXPECTATION_STATUS = Object.freeze({
  OPEN: 'OPEN',
  WAITING: 'WAITING',
  RESOLVED: 'RESOLVED',
  OVERDUE: 'OVERDUE',
});

const CLAIM_TYPES = Object.freeze({
  AO: 'AO',
  ACCOUNT: 'ACCOUNT',
  CONTACT: 'CONTACT',
  RELATIONSHIP: 'RELATIONSHIP',
  EVENT: 'EVENT',
  SIGNAL: 'SIGNAL',
  NEXT_EXPECTED_EVENT: 'NEXT_EXPECTED_EVENT',
  EXPECTED_WINDOW: 'EXPECTED_WINDOW',
  PIPELINE_IMPLICATION: 'PIPELINE_IMPLICATION',
  OWNERSHIP: 'OWNERSHIP',
  ACTIVITY: 'ACTIVITY',
  PAIN_SIGNAL: 'PAIN_SIGNAL',
  OPPORTUNITY_CONTEXT: 'OPPORTUNITY_CONTEXT',
  NEXT_ACTION: 'NEXT_ACTION',
  DUE_WINDOW: 'DUE_WINDOW',
  PARTIAL_FACT: 'PARTIAL_FACT',
  UNKNOWN_FIELD: 'UNKNOWN_FIELD',
  OPERATOR_CORRECTION: 'OPERATOR_CORRECTION',
});

module.exports = {
  SOURCE_TYPES,
  RESOLUTION,
  SAFETY_CLASS,
  EXPECTATION_STATUS,
  CLAIM_TYPES,
};
