'use strict';

const ATTENTION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  WAITING: 'WAITING',
  BLOCKED: 'BLOCKED',
  OVERDUE: 'OVERDUE',
  RESOLVED: 'RESOLVED',
  SUPERSEDED: 'SUPERSEDED',
});

const REVIEW_TRIGGER = Object.freeze({
  TIME: 'TIME',
  STATE: 'STATE',
  EVIDENCE: 'EVIDENCE',
  MANUAL: 'MANUAL',
});

const AUDIENCE_TIER = Object.freeze({
  MAX_HANDLES: 'MAX_HANDLES',
  AO_HANDLES: 'AO_HANDLES',
  OPERATOR_VISIBLE: 'OPERATOR_VISIBLE',
  WAITING_SILENT: 'WAITING_SILENT',
});

const UNRESOLVED_STATUSES = Object.freeze([
  ATTENTION_STATUS.ACTIVE,
  ATTENTION_STATUS.WAITING,
  ATTENTION_STATUS.BLOCKED,
  ATTENTION_STATUS.OVERDUE,
]);

module.exports = {
  ATTENTION_STATUS,
  REVIEW_TRIGGER,
  AUDIENCE_TIER,
  UNRESOLVED_STATUSES,
};
