'use strict';

/** @typedef {(
 *   | 'DISCOVERED'
 *   | 'ELIGIBLE'
 *   | 'INELIGIBLE'
 *   | 'SELECTED'
 *   | 'BACKFILLED'
 *   | 'REPLAYED'
 *   | 'DATA_INSUFFICIENT'
 * )} ResearchCandidateStatus */

/** @typedef {'stronger' | 'failure' | 'mixed_fixture' | 'unknown'} SelectionCategory */

const RESEARCH_CANDIDATE_STATUSES = Object.freeze([
  'DISCOVERED',
  'ELIGIBLE',
  'INELIGIBLE',
  'SELECTED',
  'BACKFILLED',
  'REPLAYED',
  'DATA_INSUFFICIENT',
]);

const VALIDATION_COHORT_001_ID = 'cohort-signal-v1-validation-001';
const VALIDATION_COHORT_001_SELECTION_VERSION = 'validation-001-selection-v1';
const VALIDATION_COHORT_001_TARGET_SIZE = 40;
const VALIDATION_COHORT_001_PER_CATEGORY = 20;

const VALIDATION_COHORT_002_ID = 'cohort-signal-v1-validation-002';
const VALIDATION_COHORT_002_SELECTION_VERSION = 'validation-002-selection-v1';
const VALIDATION_COHORT_002_TARGET_SIZE = 40;
const VALIDATION_COHORT_002_PER_CATEGORY = 20;

const VALIDATION_COHORT_003_ID = 'cohort-signal-v1-validation-003';
const VALIDATION_COHORT_003_SELECTION_VERSION = 'validation-003-selection-v1';
const VALIDATION_COHORT_003_TARGET_SIZE = 50;

const PROSPECTIVE_COHORT_001_ID = 'cohort-signal-v1-prospective-001';

module.exports = {
  RESEARCH_CANDIDATE_STATUSES,
  VALIDATION_COHORT_001_ID,
  VALIDATION_COHORT_001_SELECTION_VERSION,
  VALIDATION_COHORT_001_TARGET_SIZE,
  VALIDATION_COHORT_001_PER_CATEGORY,
  VALIDATION_COHORT_002_ID,
  VALIDATION_COHORT_002_SELECTION_VERSION,
  VALIDATION_COHORT_002_TARGET_SIZE,
  VALIDATION_COHORT_002_PER_CATEGORY,
  VALIDATION_COHORT_003_ID,
  VALIDATION_COHORT_003_SELECTION_VERSION,
  VALIDATION_COHORT_003_TARGET_SIZE,
  PROSPECTIVE_COHORT_001_ID,
};
