'use strict';

const PROSPECTIVE_COHORT_001_ID = 'cohort-signal-v1-prospective-001';
const VALIDATION_COHORT_003_ID = 'cohort-signal-v1-validation-003';

const PROSPECTIVE_TARGET_SAMPLE_SIZE = 50;
const PROSPECTIVE_TOKEN_EPISODE_COOLDOWN_HOURS = 24;

const PROSPECTIVE_FROZEN_HYPOTHESIS = Object.freeze({
  name: 'INDEPENDENT_CONVERGENCE',
  minProvenIndependentClusters: 2,
  convergenceWindowMinutes: 30,
  primaryExecutionDelaySeconds: 60,
  executionDelaySeconds: Object.freeze([15, 30, 60, 180, 300]),
  passMultiple: 2.0,
  failMultiple: 0.7,
  horizonHours: 24,
});

const PROSPECTIVE_RESEARCH_DEFINITION_VERSION = 'signal-research-v1-prospective-001';
const PROSPECTIVE_FEATURE_VERSION = 'signal-features-v1';
const PROSPECTIVE_PARSER_VERSION = 'signal-ca-parser-v1';

const JOB_STATUS = Object.freeze({
  PENDING_DELAY_CAPTURE: 'PENDING_DELAY_CAPTURE',
  PENDING_OUTCOME: 'PENDING_OUTCOME',
  COMPLETE: 'COMPLETE',
  DATA_INSUFFICIENT: 'DATA_INSUFFICIENT',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
});

const CLUSTER_RELATIONSHIP = Object.freeze({
  INDEPENDENT: 'INDEPENDENT',
  CORRELATED: 'CORRELATED',
  UNKNOWN: 'UNKNOWN',
});

const SOURCE_ROLES = Object.freeze(['DISCOVERY', 'CALLER', 'AMPLIFIER', 'UNKNOWN']);

const DATA_CLASS = Object.freeze({
  EMPIRICAL: 'EMPIRICAL',
  PROCEDURAL: 'PROCEDURAL',
});

const COHORT_MODE = Object.freeze({
  PROSPECTIVE: 'PROSPECTIVE',
  HISTORICAL: 'HISTORICAL',
});

module.exports = {
  PROSPECTIVE_COHORT_001_ID,
  VALIDATION_COHORT_003_ID,
  PROSPECTIVE_TARGET_SAMPLE_SIZE,
  PROSPECTIVE_TOKEN_EPISODE_COOLDOWN_HOURS,
  PROSPECTIVE_FROZEN_HYPOTHESIS,
  PROSPECTIVE_RESEARCH_DEFINITION_VERSION,
  PROSPECTIVE_FEATURE_VERSION,
  PROSPECTIVE_PARSER_VERSION,
  JOB_STATUS,
  CLUSTER_RELATIONSHIP,
  SOURCE_ROLES,
  DATA_CLASS,
  COHORT_MODE,
};
