'use strict';

const SEMANTIC_TYPE = Object.freeze({
  ACTIVE_ENTITY: 'ACTIVE_ENTITY',
  ACTIVE_CONTACT: 'ACTIVE_CONTACT',
  RECENT_THREAD: 'RECENT_THREAD',
  REFERENCE_BINDING: 'REFERENCE_BINDING',
  CORRECTION_CONTEXT: 'CORRECTION_CONTEXT',
  TEMPORAL_CONTEXT: 'TEMPORAL_CONTEXT',
  OPEN_QUESTION: 'OPEN_QUESTION',
  OPEN_COMMITMENT: 'OPEN_COMMITMENT',
});

const DEFAULT_TTL_MS = Object.freeze({
  ACTIVE_ENTITY: 7 * 24 * 60 * 60 * 1000,
  ACTIVE_CONTACT: 7 * 24 * 60 * 60 * 1000,
  RECENT_THREAD: 7 * 24 * 60 * 60 * 1000,
  REFERENCE_BINDING: 3 * 24 * 60 * 60 * 1000,
  CORRECTION_CONTEXT: 14 * 24 * 60 * 60 * 1000,
  TEMPORAL_CONTEXT: 7 * 24 * 60 * 60 * 1000,
  OPEN_QUESTION: 2 * 24 * 60 * 60 * 1000,
  OPEN_COMMITMENT: 14 * 24 * 60 * 60 * 1000,
});

const MAX_ACTIVE_CONTACTS = 8;
const MAX_ACTIVE_ENTITIES = 8;
const MAX_RECENT_THREADS = 12;

module.exports = {
  SEMANTIC_TYPE,
  DEFAULT_TTL_MS,
  MAX_ACTIVE_CONTACTS,
  MAX_ACTIVE_ENTITIES,
  MAX_RECENT_THREADS,
};
